export interface Variant {
	id: string;
	gene: string;
	transcript_id: string;
	position: number;
	chrom: string;
	rsid: string;
	REF: string;
	ALT: string;
	cnomen: string;
	pnomen: string;
	function: string;
	location: string;
	coverage: string;
	// zygosity: string; 
	clinvar: string;
	gnomad_ALL: string;
	gnomad: string;
	gnomad_AMR: string;
	gnomad_AFR: string;
	cosmicID: string;
	classification: string;
	gnomAD_AMR: string,
	Consequence: string,
	EXON: string,
	INTRON: string,
	DOMAINS: string,
	gnomAD_genome_AMR: string,
	gnomADe_AMR: string,
	CLINSIG: string,
	NEW_CLINSIG: string,
	CLNACC: string,
	SOMATIC: string,
	cosmics: string,
	SIFT_score: string,
	Polyphen2_HDIV_score: string,
	CADD_PHRED: string,
	PUBMED: string,
	gold_stars: number,
	review_status: string,
	Clinvar_VARIANT_ID: string,
	gene_omim: string,
	GeneSplicer: string,
	gnomADe_AFR: string,
	gnomAD_genome_AFR: string,
	"1000g_AFR_AF": string,
	"1000g_AMR_AF": string,
	gnomADe_EAS: string,
	gnomAD_genome_EAS: string,
	gnomADe_SAS: string,
	"1000g_SAS_AF": string,
	gnomADe_ASJ: string,
	gnomAD_genome_ASJ: string,
	gnomADe_FIN: string,
	gnomAD_genome_FIN: string,
	"1000g_EUR_AF": string,
	gnomADe_NFE: string,
	gnomAD_genome_NFE: string,
	gnomADe_OTH: string,
	gnomADe_ALL: string,
	gnomAD_genome_ALL: string,
	"1000g_AF": string,
	"1000g_EAS_AF": string,
	gnomAD_genome_OTH: string,
	CANONICAL: string,
	HGNC_PRE_SYMBOL: string,
	HGNC_SYMONYMS: string
}
